// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.887
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Question() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-white p-5 rounded-lg shadow w-full md:w-1/2 relative\"><div class=\"absolute top-4 right-4 text-lg font-semibold text-blue-700\">Очки: 125</div><h2 class=\"text-xl font-semibold text-gray-800 mb-4\">Текущий вопрос</h2><!-- Таймер --><div class=\"w-full bg-gray-200 rounded-full h-3 mb-4\"><div id=\"progressBar\" class=\"bg-blue-500 h-3 rounded-full\" style=\"width: 90%;\"></div></div><!-- Вопрос --><input type=\"text\" class=\"w-full px-4 py-2 mb-4 border border-gray-300 rounded text-base\" placeholder=\"Введите вопрос\"><!-- Варианты ответа --><div class=\"space-y-3 mb-4\"><label class=\"flex items-center space-x-3 text-lg\"><input type=\"checkbox\" class=\"text-blue-600 w-5 h-5\"> <span>Ответ A</span></label> <label class=\"flex items-center space-x-3 text-lg\"><input type=\"checkbox\" class=\"text-blue-600 w-5 h-5\"> <span>Ответ B</span></label> <label class=\"flex items-center space-x-3 text-lg\"><input type=\"checkbox\" class=\"text-blue-600 w-5 h-5\"> <span>Ответ C</span></label> <label class=\"flex items-center space-x-3 text-lg\"><input type=\"checkbox\" class=\"text-blue-600 w-5 h-5\"> <span>Ответ D</span></label></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, templ.JSFuncCall("submitAnswer"))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button onclick=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.ComponentScript = templ.JSFuncCall("submitAnswer")
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"bg-green-500 hover:bg-green-600 text-white px-6 py-2 rounded text-base mb-4\">Ответить</button><!-- Ответившие --><div class=\"border-t pt-4 mt-4\"><h3 class=\"text-lg font-semibold mb-3\">Ответившие участники:</h3><div class=\"flex flex-wrap gap-4\"><!-- Пример участника --><div class=\"flex items-center space-x-4 bg-green-50 border border-black text-green-700 rounded px-4 py-3\"><img src=\"https://robohash.org/user5?set=set4\" alt=\"user\" class=\"w-14 h-14 rounded-full\"> <span class=\"text-lg\">Наташа</span></div><!-- Неправильный --><div class=\"flex items-center space-x-4 bg-red-50 border border-black text-red-700 rounded px-4 py-3\"><img src=\"https://robohash.org/user6?set=set4\" alt=\"user\" class=\"w-14 h-14 rounded-full\"> <span class=\"text-lg\">Сергей</span></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
